# Production profile overrides
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.syntaxcore: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
